main.datasource.url=${PG_DATASOURCE_URL}
main.datasource.username=${PG_NAME}
main.datasource.password=${PG_PASS}

woofi.bridge.base-url=${WOOFI_BRIDGE_BASE_URL}
woofi.bridge.api.key=${WOOFI_BRIDGE_API_KEY}

vaadin.productionMode=true
